### ISSUE TITLE
Error when importing .skel files

### ISSUE THREAD

**Issue by SkyNinja** [johnzero7/HaydeeTools#5]
Any time I import a .skel file, I get an error message as shown after the standard output here:

```
skel: C:\Steam\steamapps\common\Haydee\Outfits\Haydee\Haydee.skel
Signature: HD_CHUNK
(  0.0010 sec |   0.0010 sec) Importing dmesh
  (  0.0020 sec |   0.0010 sec) Build armature
Importing Armature 77 bones
    (  0.0040 sec |   0.0020 sec) create bones
      (  0.0250 sec |   0.0200 sec) create bones end
    (  0.0260 sec |   0.0240 sec) parenting bones
      (  0.0440 sec |   0.0180 sec) parenting bones end
    (  0.0450 sec |   0.0430 sec) aligning bones
      (  0.0680 sec |   0.0220 sec) aligning bones end
    (  0.0730 sec |   0.0710 sec) Build armature end
  (  0.0750 sec |   0.0740 sec) Finish Importing dmesh
Progress: 100.00%

Traceback (most recent call last):
  File "C:\Users\Brett\AppData\Roaming\Blender Foundation\Blender\2.80\scripts\addons\HaydeeTools-master\HaydeeImporter.py", line 420, in execute
    return read_skel(self, context, self.filepath)
  File "C:\Users\Brett\AppData\Roaming\Blender Foundation\Blender\2.80\scripts\addons\HaydeeTools-master\HaydeeImporter.py", line 368, in read_skel
    boneGroup = armature_ob.pose.bone_groups.new(groupName)
TypeError: BoneGroups.new(): required parameter "name" to be a keyword argument!
```

The armature seems to import perfectly well despite this, unless the addon is trying to combine the skeleton with objects already in the scene, like when importing a .skin file over a .mesh.

**Comment by johnzero7** [comment]
Corrected.
At the point of the error the armature is fully imported. After that (what was not being done) the addon creates some drivers to reproduce the behavior of the armature in Haydee.
